kabi: Add greylist check support for kernel rpm building
Patchwork-id: 45398
O-Subject: [PATCHv2 RHEL6.3 2/2] kabi: Add greylist check support for kernel
	rpm building
Bugzilla: 613726
RH-Acked-by: Don Zickus <dzickus@redhat.com>
RH-Acked-by: Laszlo Ersek <lersek@redhat.com>

description
===========
Adding support to monitor list of functions which are not
on the KABI whitelist, but partners use them inside their
modules and are interested in knowing wether they changed.
This is currently known as 'greylist'.

During the kernel rpm build, the whitelist data are checked,
and the build is aborted if the build mismatch the KABI.

Adding same framework and check for greylist, but letting
the build to continue in case of mismatch. The greylist
status is part of the build.log separated by following lines:

**** kABI: greylist checking start ****
...
**** kABI: greylist checking stop  ****

It'd be nice to have separate log file for KABI output, but
I'm not sure if that's more TODO or a wish.. :)

brew build
==========
https://brewweb.devel.redhat.com/taskinfo?taskID=4011655

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>

diff --git a/redhat/kernel.spec.template b/redhat/kernel.spec.template
--- a/redhat/kernel.spec.template
+++ b/redhat/kernel.spec.template
@@ -564,6 +564,10 @@ Source30: Module.kabi_i686
 Source31: Module.kabi_ppc64
 Source32: Module.kabi_s390x
 Source33: Module.kabi_x86_64
+Source34: Module.kabi_greylist_i686
+Source35: Module.kabi_greylist_ppc64
+Source36: Module.kabi_greylist_s390x
+Source37: Module.kabi_greylist_x86_64
 
 %%CONFIGS%%
 
@@ -1133,15 +1137,26 @@ hwcap 1 nosegneg"
     rm -f %{_tmppath}/kernel-$KernelVer-kabideps
     %_sourcedir/kabitool -s Module.symvers -o %{_tmppath}/kernel-$KernelVer-kabideps
 
+    # whitelist checking
+    # if this one fails, the build fails
     echo "**** kABI checking is enabled in kernel SPEC file. ****"
     chmod 0755 $RPM_SOURCE_DIR/check-kabi
-    if [ -e $RPM_SOURCE_DIR/Module.kabi_%{_target_cpu}$Flavour ]; then
-        cp $RPM_SOURCE_DIR/Module.kabi_%{_target_cpu}$Flavour $RPM_BUILD_ROOT/Module.kabi
-        $RPM_SOURCE_DIR/check-kabi -k $RPM_BUILD_ROOT/Module.kabi -s Module.symvers || exit 1
-        rm $RPM_BUILD_ROOT/Module.kabi # for now, don't keep it around.
+    whitelist=$RPM_SOURCE_DIR/Module.kabi_%{_target_cpu}$Flavour
+    if [ -e $whitelist ]; then
+        $RPM_SOURCE_DIR/check-kabi -k $whitelist -s Module.symvers || exit 1
     else
         echo "**** NOTE: Cannot find reference Module.kabi file. ****"
     fi
+
+    # greylist checking
+    # if this one fails, we go on with warnings in build log
+    greylist=$RPM_SOURCE_DIR/Module.kabi_greylist_%{_target_cpu}$Flavour
+    if [ -e $greylist ]; then
+        echo "**** kABI: greylist checking start ****"
+        $RPM_SOURCE_DIR/check-kabi -k $greylist -s Module.symvers
+        echo "**** kABI: greylist checking stop  ****"
+    fi
+
 %endif
     # Ensure the kabideps file always exists for the RPM ProvReq scripts
     touch %{_tmppath}/kernel-$KernelVer-kabideps
