internal rh-test: support args and add network test
Patchwork-id: 23787
O-Subject: [PATCH RHEL-6] internal rh-test: support args and add network test
Bugzilla:

When adding support for the network test, I realized it made sense to
support args for the type of NIC you wanted to test.  I tweaked the
Makefile.test to handle this and applied the same rules to the filesystem
test.

The filesytem test has been updated to handle the new arg and test across
all the arches (though xfs is disabled for non-x86_64 arches).  I have run
this test multiple times with success.  Eric S. is still fixing a couple of
problems discovered with the testsuite but it works quite well and I would
encourage filesystem folks to start utilizing it.

The netowrk testsuite is simple right now.  Just runs netperf between two
machines and checks to make sure the throughput is within 75% of the
expected NIC speed.  It would be nice to add to the testsuite.  *hint*
*hint*.  This test currently only runs on x86_64 as this is where the
majority of the NICs run.

I also changed the 'tests' file to use 'rhtests' instead per Vivek's
suggestion.

Remember to run these tests use either

edit $gittree/rhtests (ie echo "filesystem ext4" > rhtests)
make rh-brew-test
  OR
TASK=$TASK make rh-test
(where $TASK is a scratch build task number or None to use a released build)

Please let me know if you have any issues.

Signed-off-by: Don Zickus <dzickus@redhat.com>
Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>

diff --git a/redhat/Makefile.test b/redhat/Makefile.test
--- a/redhat/Makefile.test
+++ b/redhat/Makefile.test
@@ -4,17 +4,23 @@ NAME=kernel
 VERSION=2.6.32
 FAMILY=RedHatEnterpriseLinux6
 TMPFILE="tests/job.xml"
+TMPFILE2="tests/tmp.xml"
 USER_ID ?= $(shell /usr/kerberos/bin/klist|awk '/Default principal: /{print tolower($$3)}; ')
 TASK_USER ?= $(shell echo "${USER_ID}" | cut -d'@' -f1)
 
 #find tests
-TESTFILE=../tests
+TNAME=rhtests
+TESTFILE=../$(TNAME)
 ifneq ($(wildcard $(TESTFILE)),)
-TEST:=$(shell cat $(TESTFILE))
+TEST:=$(shell awk '{print $$1}' $(TESTFILE))
+TESTARG:=$(shell awk '{print $$2}' $(TESTFILE))
 TESTNAME:=$(shell echo "tests/$(TEST).xml")
+TESTARG_found:=$(shell sed -n '/^\#/d; /%%TESTARGBEGIN%%/,/%%TESTARGEND%%/p' $(TESTNAME)|grep -q "^$(TESTARG)$$" && echo "good")
 else
 TEST:=None
+TESTARG:=None
 TESTNAME:=None
+TESTARG_found:=None
 endif
 $(info TEST is "$(TEST)". Update '$(shell dirname $(REDHAT))/tests' to change.)
 
@@ -26,18 +32,32 @@ endif
 
 pre-xml-check:
 	@(if test -z "$(USER_ID)"; then \
+		echo ""; \
 		echo "Please setup Kerberos for detecting USER_ID"; \
+		echo ""; \
 		exit 1; \
 	fi)
 	@(if test "$(TESTNAME)" == "None" || ! test -f "$(TESTNAME)"; then \
-		echo "INVALID test: $(TEST)"; \
-		echo "Please use something from redhat/tests in the 'tests' file"; \
+		echo ""; \
+		echo "INVALID test: $(TEST)."; \
+		echo "Please use something from redhat/tests in the '$(TNAME)' file"; \
+		echo ""; \
+		exit 1; \
+	fi)
+	@(if test "$(TESTARG_found)" != "good"; then \
+		echo ""; \
+		echo "INVALID test argument: $(TESTARG)."; \
+		echo "Please add one of the following args to '$(TNAME)' for test $(TESTNAME)"; \
+		sed -n '/^#/d; /%%TESTARGBEGIN%%/,/%%TESTARGEND%%/p' $(TESTNAME)| grep -v "^%%"; \
+		echo ""; \
 		exit 1; \
 	fi)
 	@(if test -z "$(TASK)"; then \
+		echo ""; \
 		echo "TASK number needed"; \
 		echo "set TASK=<num>/None for make rh-test otherwise make rh-brew-test should"; \
 		echo "automagically pick it up"; \
+		echo ""; \
 		exit 1; \
 	fi)
 
@@ -53,6 +73,12 @@ setup-xml:
 	@echo "  RELEASE: $(RELEASE)"
 	@echo "  TASK_USER: $(TASK_USER)"
 	@echo "  TASK: $(TASK)"
+	@#copy to temp file to modify if need be
+	@cp $(TESTNAME) $(TMPFILE2)
+	@#remove rhts restriction in 'any' case
+	@(if test "$(TESTARG)" == "any"; then \
+		sed -i '/whiteboard/n;/%%TESTARG%%/d' $(TMPFILE2); \
+	fi)
 	@(sed -e 's/%%USER_ID%%/$(USER_ID)/g;' \
 	      -e 's/%%DISTROTAG%%/$(DISTROTAG)/g;' \
 	      -e 's/%%FAMILY%%/$(FAMILY)/g;' \
@@ -60,8 +86,11 @@ setup-xml:
 	      -e 's/%%KVERSION%%/$(KVERSION)/g;' \
 	      -e 's,%%TASK_USER%%,$(TASK_USER),g;' \
 	      -e 's,%%TASK%%,$(TASK),g;' \
-	$(TESTNAME) > $(TMPFILE);)
+	      -e '/%%TESTARGBEGIN%%/,/%%TESTARGEND%%/d;' \
+	      -e 's/%%TESTARG%%/$(TESTARG)/g;' \
+	$(TMPFILE2) > $(TMPFILE);)
 	@echo "Parsed redhat/$(TESTNAME) -> redhat/$(TMPFILE)"
+	@rm $(TMPFILE2)
 
 .PHONY: rh-test
 rh-test: TASK ?= $(shell test -n "$(OUTFILE)" && awk '/Created task:/{print $$3}' $(OUTFILE))
